// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route.proto

package route;

public interface HeartBeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:route.HeartBeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string life = 1;</code>
   * @return The life.
   */
  java.lang.String getLife();
  /**
   * <code>string life = 1;</code>
   * @return The bytes for life.
   */
  com.google.protobuf.ByteString
      getLifeBytes();
}
